### ISSUE TITLE
抖音无法获取弹幕数据

### ISSUE THREAD

**Issue by wisdomTechnologyIoT** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#105]
抖音无法获取弹幕数据其他的平台可以这个怎么解决大佬

**Comment by 1962247851** [comment]
版本、房间号、Client配置、有无报错🙂

**Comment by wisdomTechnologyIoT** [comment]
抖音的包是0.4.1 房间号对过 但是他们的平台可以获取数据

**Comment by wisdomTechnologyIoT** [comment]
抖音的包是0.4.1 房间号对过 但是其他的平台可以获取数据

**Comment by wisdomTechnologyIoT** [comment]
枯了

**Comment by wisdomTechnologyIoT** [comment]
没显示报错

**Comment by 1962247851** [comment]
换个直播间也收不到吗

**Comment by wisdomTechnologyIoT** [comment]
都没效果

**Comment by 1962247851** [comment]
但我好像复现不了😢，本地跟服务器上都正常的

**Comment by wisdomTechnologyIoT** [comment]
你那边真正常获取数据吗

**Comment by wisdomTechnologyIoT** [comment]
你那边能正常获取数据吗

**Comment by 1962247851** [comment]
https://barragefly.ordinaryroad.tech:7000/barrage?taskIds=1767367738595041280

**Comment by wisdomTechnologyIoT** [comment]
为啥你这房间号这么长

**Comment by 1962247851** [comment]
那个是任务id，不是房间号

**Comment by wisdomTechnologyIoT** [comment]
![image](https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/110519463/a1ebe2ed-a413-45a9-ab3b-8ac74132481c)
连上了就这样子 没有数据

**Comment by 1962247851** [comment]
哪个直播间

**Comment by wisdomTechnologyIoT** [comment]
这个 667192034586 不过全部的直播间都是这样子

**Comment by 1962247851** [comment]
正常<img width="929" alt="image" src="https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/43869694/90bda409-5b21-48b4-b8e3-9154b0845b24">

**Comment by 1962247851** [comment]
https://barragefly.ordinaryroad.tech:7000/barrage?taskIds=1773265817600876544

**Comment by 1962247851** [comment]
代码贴一下看看

**Comment by wisdomTechnologyIoT** [comment]
if (liveInfo.getLiveType() == 1 && liveInfo.getLiveRoomNumber() != null) {
            LIVE_TYPE = liveInfo.getLiveType();
            String cookie = System.getenv("cookie");
            log.error("cookie: {}", cookie);
            DouyinLiveChatClientConfig config = DouyinLiveChatClientConfig.builder()
                    // TODO 浏览器Cookie
                    .cookie(cookie)
                    .roomId(liveInfo.getLiveRoomNumber())
                    .build();
            douYinClient = new DouyinLiveChatClient(config, new IDouyinMsgListener() {
                /**进入直播间*/
                @Override
                public void onEnterRoomMsg(DouyinBinaryFrameHandler binaryFrameHandler, DouyinEnterRoomMsg msg) {
                    liveMessageVo messageVo = new liveMessageVo();
                    messageVo.setType(1);
                    messageVo.setUserName(msg.getUsername());
                    System.out.println("进入直播间");
                    webSocket.sendMessageAll(gson.toJson(messageVo));
                }

                /**收到弹幕*/
                @Override
                public void onDanmuMsg(DouyinBinaryFrameHandler binaryFrameHandler, DouyinDanmuMsg msg) {
                    liveMessageVo messageVo = new liveMessageVo();
                    messageVo.setType(2);
                    messageVo.setUserName(msg.getUsername());
                    messageVo.setMessageContent(msg.getContent());
                    webSocket.sendMessageAll(gson.toJson(messageVo));
                }

                /**收到礼物*/
                @Override
                public void onGiftMsg(DouyinBinaryFrameHandler binaryFrameHandler, DouyinGiftMsg msg) {
                    //判断礼物数量是否大于0
                    if (msg.getGiftCount() > 0) {
                        liveMessageVo messageVo = new liveMessageVo();
                        messageVo.setType(3);
                        messageVo.setUserName(msg.getUsername());
                        messageVo.setMessageContent(msg.getGiftName());
                        messageVo.setCount(msg.getGiftCount());
                        webSocket.sendMessageAll(gson.toJson(messageVo));
                        System.out.println("礼物内容" + msg);
                    }

                }
            });
            //开启抓取数据
            douYinClient.connect();

            final AtomicInteger status = new AtomicInteger(0);
            final CountDownLatch latch = new CountDownLatch(1);
            // 客户端连接状态回调
            douYinClient.addStatusChangeListener(new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent evt) {
                    System.out.println(evt);
                    System.out.println(evt.getPropertyName());
                    if (evt.getNewValue().equals(ClientStatusEnums.CONNECT_FAILED)) {
                        System.out.println("连接失败");
                        status.set(1);
                        latch.countDown();  // 表明回调已执行
                    }
                }
            });
            //锁存器 2秒后解锁
            latch.await(2, TimeUnit.SECONDS);
            if (status.get() == 1) {
                return CompletableFuture.completedFuture(new Result().startError());
            } else {
                System.out.println("开始直播");
                return CompletableFuture.completedFuture(new Result().startSuccess());
            }
        }

**Comment by wisdomTechnologyIoT** [comment]
if (liveInfo.getLiveType() == 1 && liveInfo.getLiveRoomNumber() != null) {
            LIVE_TYPE = liveInfo.getLiveType();
            String cookie = System.getenv("cookie");
            log.error("cookie: {}", cookie);
            DouyinLiveChatClientConfig config = DouyinLiveChatClientConfig.builder()
                    // TODO 浏览器Cookie
                    .cookie(cookie)
                    .roomId(liveInfo.getLiveRoomNumber())
                    .build();
            douYinClient = new DouyinLiveChatClient(config, new IDouyinMsgListener() {
                /**进入直播间*/
                @Override
                public void onEnterRoomMsg(DouyinBinaryFrameHandler binaryFrameHandler, DouyinEnterRoomMsg msg) {
                    liveMessageVo messageVo = new liveMessageVo();
                    messageVo.setType(1);
                    messageVo.setUserName(msg.getUsername());
                    System.out.println("进入直播间");
                    webSocket.sendMessageAll(gson.toJson(messageVo));
                }

                /**收到弹幕*/
                @Override
                public void onDanmuMsg(DouyinBinaryFrameHandler binaryFrameHandler, DouyinDanmuMsg msg) {
                    liveMessageVo messageVo = new liveMessageVo();
                    messageVo.setType(2);
                    messageVo.setUserName(msg.getUsername());
                    messageVo.setMessageContent(msg.getContent());
                    webSocket.sendMessageAll(gson.toJson(messageVo));
                }

                /**收到礼物*/
                @Override
                public void onGiftMsg(DouyinBinaryFrameHandler binaryFrameHandler, DouyinGiftMsg msg) {
                    //判断礼物数量是否大于0
                    if (msg.getGiftCount() > 0) {
                        liveMessageVo messageVo = new liveMessageVo();
                        messageVo.setType(3);
                        messageVo.setUserName(msg.getUsername());
                        messageVo.setMessageContent(msg.getGiftName());
                        messageVo.setCount(msg.getGiftCount());
                        webSocket.sendMessageAll(gson.toJson(messageVo));
                        System.out.println("礼物内容" + msg);
                    }

                }
            });
            //开启抓取数据
            douYinClient.connect();

            final AtomicInteger status = new AtomicInteger(0);
            final CountDownLatch latch = new CountDownLatch(1);
            // 客户端连接状态回调
            douYinClient.addStatusChangeListener(new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent evt) {
                    System.out.println(evt);
                    System.out.println(evt.getPropertyName());
                    if (evt.getNewValue().equals(ClientStatusEnums.CONNECT_FAILED)) {
                        System.out.println("连接失败");
                        status.set(1);
                        latch.countDown();  // 表明回调已执行
                    }
                }
            });
            //锁存器 2秒后解锁
            latch.await(2, TimeUnit.SECONDS);
            if (status.get() == 1) {
                return CompletableFuture.completedFuture(new Result().startError());
            } else {
                System.out.println("开始直播");
                return CompletableFuture.completedFuture(new Result().startSuccess());
            }
        }

**Comment by 1962247851** [comment]
感觉唯一可能有问题的就是`.roomId(liveInfo.getLiveRoomNumber())`设置房间号这行代码，你试试输出一下实际配置的房间号是多少

**Comment by wisdomTechnologyIoT** [comment]
输出的是正常的直播间号 String类型

**Comment by 1962247851** [comment]
`https://live.douyin.com/房间号`可以正常打开直播间吗

**Comment by wisdomTechnologyIoT** [comment]
可以

**Comment by 1962247851** [comment]
添加一下`onMsg`消息回调
```java
@Override
            public void onMsg(IMsg msg) {
                log.debug("收到{}消息 {}", msg.getClass(), msg);
            }
```

**Comment by wisdomTechnologyIoT** [comment]
加了好像没有回调信息输出

**Comment by 1962247851** [comment]
打印一下消息监听器个数，`System.out.println("MsgListener Count: " + client.getMsgListeners().size());`
把配置cookie的那一行注释掉

**Comment by 1962247851** [comment]
再不行我也没法了😭

**Comment by wisdomTechnologyIoT** [comment]
![image](https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/110519463/e275984e-21bd-4358-935d-1ce413b2e4e2)
消息监听器一个

**Comment by wisdomTechnologyIoT** [comment]
傻眼了 好像也没问题

**Comment by wisdomTechnologyIoT** [comment]
老哥有联系方式吗 有偿 不会让你白帮忙

**Comment by 1962247851** [comment]
[QQ频道](https://pd.qq.com/s/3id0n7fvs)
