### ISSUE TITLE
Bilibili模块的依赖缺失

### ISSUE THREAD

**Issue by KByteArray** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#108]
### 你使用了哪个版本？ | Which version did you use?
Latest

### 预期行为 | Expected behavior
在项目(Gradle)引入live-chat-client-bilibili模块后编写相关代码正常连接

### 实际行为 | Actual behavior
在项目引入live-chat-client-bilibili模块后编写相关代码连接时报错缺少`com.aayushatharva.brotli4j:native-windows-x86_64:1.16.0`依赖
在引入该依赖后可以正常使用，如果这是正确用法的话可以文档里面加一下*

### 原因分析（如果可以） | Cause analysis (if possible)
没用maven-shade-plugin插件把依赖打包进最终产物里面(?)

**Comment by 1962247851** [comment]
确实有这个问题，详见： https://github.com/hyperxpro/Brotli4j?tab=readme-ov-file#gradle
