### ISSUE TITLE
douyin本人使用发现累计点赞数 累计观看人数显示null

### ISSUE THREAD

**Issue by SoYoungxSoWhat** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#147]
Xxxxxx房间号  统计信息 累计点赞数: null, 当前观看人数: 29, 累计观看人数: null
douyin本人使用发现累计点赞数 累计观看人数显示null

使用的这段代码
    @Override
    public void onRoomStatsMsg(DouyinBinaryFrameHandler binaryFrameHandler, DouyinRoomStatsMsg msg) {
        IDouyinMsgListener.super.onRoomStatsMsg(binaryFrameHandler, msg);
        log.info("{} 统计信息 累计点赞数: {}, 当前观看人数: {}, 累计观看人数: {}", binaryFrameHandler.getRoomId(), msg.getLikedCount(), msg.getWatchingCount(), msg.getWatchedCount());
    }

**Comment by 1962247851** [comment]
https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client

**Comment by 1962247851** [comment]
每个数据包里面的统计信息不一样，请判断是否null后使用
