### ISSUE TITLE
🚀 一些功能。。。 | [Feature]Some feature...

### ISSUE THREAD

**Issue by weikecloud** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#156]
#### 您使用的场景？ | 1. Your usage scenarios?
本地部署或者服务器部署

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
有部署文档，或者是可以docker部署

**Comment by 1962247851** [comment]
没太理解，这个项目是作为依赖引用到自己的项目中的，不知道你找的是不是这个：https://barragefly.ordinaryroad.tech

**Comment by weikecloud** [comment]
> 没太理解，这个项目是作为依赖引用到自己的项目中的，不知道你找的是不是这个：https://barragefly.ordinaryroad.tech

对，就是这个，感谢
