### ISSUE TITLE
虎牙守护开通事件

### ISSUE THREAD

**Issue by 727729853** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#167]
官网地址：https://dev.huya.com/docs/miniapp/dev/sdk/hy-ext-context-on-open-guardian-notice/
没有找到对应事件的枚举，能否添加？

**Comment by 727729853** [comment]
找到了。GuardianPresenterInfoNotice

**Comment by 1962247851** [comment]
👍

**Comment by 1962247851** [comment]
最简单的方法，自己开个直播间，把监听打开，然后自己触发一下你那个活动，看能收到什么消息
