### ISSUE TITLE
「虎牙消息解码」🙋【 问题交流】解析后的数据存在乱码

### ISSUE THREAD

**Issue by 727729853** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#169]
@Override
			public void onOtherCmdMsg(HuyaCmdEnum cmd, ICmdMsg<HuyaCmdEnum> cmdMsg) {
				if (Objects.requireNonNull(cmd) == HuyaCmdEnum.GuardianPresenterInfoNotice) {
					logger.info("监听到守护");
					byte[] dataBytes = new byte[0];
					if (cmdMsg instanceof WSPushMessage) {
						WSPushMessage wsPushMessage = (WSPushMessage) cmdMsg;
						dataBytes = wsPushMessage.getDataBytes();
					} else if (cmdMsg instanceof WSMsgItem) {
						WSMsgItem wsMsgItem = (WSMsgItem) cmdMsg;
						dataBytes = wsMsgItem.getSMsg();
					}
					String body = new String(dataBytes, StandardCharsets.UTF_8);
					logger.info("解析后的内容:{}", body);
					
				}
			}

解析后的内容存在乱码，例如：解析后的内容:  K�}童锦程【798】 3  )�>3Fsummer\`|��ahttps://huyaimg.msstatic.com/avatar/1061/66/1b4c1b90aeabdc333212ef43f85007_180_135.jpg?1584006479�u��ahttps://huyaimg.msstatic.com/avatar/1073/f7/5d111b33a50f1d18c09d854a4436ff_180_135.jpg?1649483573�gMـ�gv����初爱守护�

具体原因是什么？存在二进制数据还是html？

**Comment by 727729853** [comment]
`			@Override
			public void onOtherCmdMsg(HuyaCmdEnum cmd, ICmdMsg<HuyaCmdEnum> cmdMsg) {
				if (Objects.requireNonNull(cmd) == HuyaCmdEnum.GuardianPresenterInfoNotice) {
					logger.info("监听到守护");
					byte[] dataBytes = new byte[0];
					if (cmdMsg instanceof WSPushMessage) {
						WSPushMessage wsPushMessage = (WSPushMessage) cmdMsg;
						dataBytes = wsPushMessage.getDataBytes();
					} else if (cmdMsg instanceof WSMsgItem) {
						WSMsgItem wsMsgItem = (WSMsgItem) cmdMsg;
						dataBytes = wsMsgItem.getSMsg();
					}
					String body = new String(dataBytes, StandardCharsets.UTF_8);
					logger.info("解析后的内容:{}", body);
				}
			}`
> 解析后的内容存在乱码，例如：解析后的内容:� ��K�}���童锦程【798】 �3 �)�>3�F�summer`�|���ahttps://huyaimg.msstatic.com/avatar/1061/66/1b4c1b90aeabdc333212ef43f85007_180_135.jpg?1584006479��u��ahttps://huyaimg.msstatic.com/avatar/1073/f7/5d111b33a50f1d18c09d854a4436ff_180_135.jpg?1649483573�gMـ�gv�������初爱守护���
> 
> 具体原因是什么？存在二进制数据还是html？

**Comment by 1962247851** [comment]
因为虎牙的消息格式是TARS，https://tarscloud.org
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/36d1b1a4-b9e7-462c-9b37-2bfa876dfe19">

**Comment by 1962247851** [comment]
消息字段可以从这里得到，然后继承`BaseHuyaMsg`写一个消息类，参考`HuyaCodecUtil`中的解码方法读取消息字段，<img width="987" alt="image" src="https://github.com/user-attachments/assets/91906b86-b040-4bf5-b08b-1bf2bf675c8a">

**Comment by 727729853** [comment]
太强了，感谢大佬。一点点心意表示支持！
![fe049a4fd60c0ae4edae4f1a82a310a7](https://github.com/user-attachments/assets/31075a6b-cc7d-4f5c-80ca-44bff692a3fd)

**Comment by 1962247851** [comment]
> 太强了，感谢大佬。一点点心意表示支持！ ![fe049a4fd60c0ae4edae4f1a82a310a7](https://private-user-images.githubusercontent.com/60378045/392320059-31075a6b-cc7d-4f5c-80ca-44bff692a3fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDY4MDQsIm5iZiI6MTczMzMwNjUwNCwicGF0aCI6Ii82MDM3ODA0NS8zOTIzMjAwNTktMzEwNzVhNmItY2M3ZC00ZjVjLTgwY2EtNDRiZmY2OTJhM2ZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEwMDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NDBmMWIwOTRkNmNkOWQ5ZGNhOTg3NTE4YWZkOTRlNjllZjA5MzljNjBmNDQ0MGQzNWUyZmY4NjE4MzMzNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-yQpGFTvK30Zsafa6dfLRipPj6uSoKes8R4slpcYP2k)

老板大气，感谢老板的支持
