### ISSUE TITLE
监听直播间，一开播发送特定的弹幕

### ISSUE THREAD

**Issue by Yoimiya-993** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#80]
#### 您使用的场景？ | 1. Your usage scenarios?
抖音直播间

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
监听某个主播的直播间，当一发现直播开播时，发送一条预编辑好内容的弹幕

**Comment by 1962247851** [comment]
经测试开播时WebSocket没有收到消息，请自行轮询访问API查询直播间状态`tech.ordinaryroad.live.chat.client.douyin.api.DouyinApis#roomInit(java.lang.Object)`

**Comment by 1962247851** [comment]
经测试开播时WebSocket没有收到消息，请自行轮询访问API查询直播间状态`tech.ordinaryroad.live.chat.client.douyin.api.DouyinApis#roomInit(java.lang.Object)`
