### ISSUE TITLE
弹幕信息抓取重复

### ISSUE THREAD

**Issue by wisdomTechnologyIoT** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#82]
不知道为啥有时候抓到的弹幕信息会重复。
如送了一个礼物返回了两条礼物数据

**Comment by 1962247851** [comment]
麻烦提供更详细的版本环境等信息，以供排查🙂

**Comment by 8824PPZ** [comment]
确实有这个问题

JDK1.8  测试虎牙霸哥直播间  
用的`HuyaLiveChatClientTest`测试的

![image](https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/36729296/8bb59992-0125-4ac5-87cf-16ec596d667b)
![image](https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/36729296/b5aba301-2d94-4b24-ad38-7f8c1a6c4cd2)

**Comment by 1962247851** [comment]
> 确实有这个问题
> 
> JDK1.8 测试虎牙霸哥直播间 用的`HuyaLiveChatClientTest`测试的
> 
> ![image](https://private-user-images.githubusercontent.com/36729296/310341353-8bb59992-0125-4ac5-87cf-16ec596d667b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDEzNTMtOGJiNTk5OTItMDEyNS00YWM1LTg3Y2YtMTZlYzU5NmQ2NjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTIxMTYwZjlkZTJjZTFhMDY2YTJhNDQ2OTQxODgwNzhhODA5YzIzNDU4NzAxYjIyNGU1MTQ3M2NiYzViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0krY6LfuM6CkWOf6C154QkvmuAjFC8fhIOxYAd48Aas) ![image](https://private-user-images.githubusercontent.com/36729296/310341520-b5aba301-2d94-4b24-ad38-7f8c1a6c4cd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDE1MjAtYjVhYmEzMDEtMmQ5NC00YjI0LWFkMzgtN2Y4YzFhNmM0Y2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Mjg3NWE1Y2VjMjZkNjIxOWMxOWU2M2YzNDQ4NjA5MWMwYzFlMWM3NzhlNDhiYTkxNDY0MjcyNGY0OWMyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ali69oGphWhEvzfPvkSbnuy36QJpSgcicQfm6gjSXo)

有没有可能这是在刷屏呢

**Comment by 1962247851** [comment]
> 不知道为啥有时候抓到的弹幕信息会重复。 如送了一个礼物返回了两条礼物数据

这是抖音平台自己的业务逻辑，框架收到啥消息返回的就是啥消息，连击送礼需要额外处理

**Comment by 8824PPZ** [comment]
> > 确实有这个问题
> > JDK1.8 测试虎牙霸哥直播间 用的`HuyaLiveChatClientTest`测试的
> > ![image](https://private-user-images.githubusercontent.com/36729296/310341353-8bb59992-0125-4ac5-87cf-16ec596d667b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDEzNTMtOGJiNTk5OTItMDEyNS00YWM1LTg3Y2YtMTZlYzU5NmQ2NjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTIxMTYwZjlkZTJjZTFhMDY2YTJhNDQ2OTQxODgwNzhhODA5YzIzNDU4NzAxYjIyNGU1MTQ3M2NiYzViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0krY6LfuM6CkWOf6C154QkvmuAjFC8fhIOxYAd48Aas) ![image](https://private-user-images.githubusercontent.com/36729296/310341520-b5aba301-2d94-4b24-ad38-7f8c1a6c4cd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDE1MjAtYjVhYmEzMDEtMmQ5NC00YjI0LWFkMzgtN2Y4YzFhNmM0Y2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Mjg3NWE1Y2VjMjZkNjIxOWMxOWU2M2YzNDQ4NjA5MWMwYzFlMWM3NzhlNDhiYTkxNDY0MjcyNGY0OWMyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ali69oGphWhEvzfPvkSbnuy36QJpSgcicQfm6gjSXo)
> 
> 有没有可能这是在刷屏呢

对比了一下，app上面也没有多条重复的，还是说app做了限制重复刷屏的显示

**Comment by 1962247851** [comment]
> > > 确实有这个问题
> > > JDK1.8 测试虎牙霸哥直播间 用的`HuyaLiveChatClientTest`测试的
> > > ![image](https://private-user-images.githubusercontent.com/36729296/310341353-8bb59992-0125-4ac5-87cf-16ec596d667b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDEzNTMtOGJiNTk5OTItMDEyNS00YWM1LTg3Y2YtMTZlYzU5NmQ2NjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTIxMTYwZjlkZTJjZTFhMDY2YTJhNDQ2OTQxODgwNzhhODA5YzIzNDU4NzAxYjIyNGU1MTQ3M2NiYzViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0krY6LfuM6CkWOf6C154QkvmuAjFC8fhIOxYAd48Aas) ![image](https://private-user-images.githubusercontent.com/36729296/310341520-b5aba301-2d94-4b24-ad38-7f8c1a6c4cd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDE1MjAtYjVhYmEzMDEtMmQ5NC00YjI0LWFkMzgtN2Y4YzFhNmM0Y2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Mjg3NWE1Y2VjMjZkNjIxOWMxOWU2M2YzNDQ4NjA5MWMwYzFlMWM3NzhlNDhiYTkxNDY0MjcyNGY0OWMyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ali69oGphWhEvzfPvkSbnuy36QJpSgcicQfm6gjSXo)
> > 
> > 有没有可能这是在刷屏呢
> 
> 对比了一下，app上面也没有多条重复的，还是说app做了限制重复刷屏的显示

前端可以控制如何展示数据，虎牙APP和网页都有屏蔽重复弹幕的开关

**Comment by 8824PPZ** [comment]
> > > > 确实有这个问题
> > > > JDK1.8 测试虎牙霸哥直播间 用的`HuyaLiveChatClientTest`测试的
> > > > ![image](https://private-user-images.githubusercontent.com/36729296/310341353-8bb59992-0125-4ac5-87cf-16ec596d667b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDEzNTMtOGJiNTk5OTItMDEyNS00YWM1LTg3Y2YtMTZlYzU5NmQ2NjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTIxMTYwZjlkZTJjZTFhMDY2YTJhNDQ2OTQxODgwNzhhODA5YzIzNDU4NzAxYjIyNGU1MTQ3M2NiYzViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0krY6LfuM6CkWOf6C154QkvmuAjFC8fhIOxYAd48Aas) ![image](https://private-user-images.githubusercontent.com/36729296/310341520-b5aba301-2d94-4b24-ad38-7f8c1a6c4cd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTM0NzAsIm5iZiI6MTcwOTY5MzE3MCwicGF0aCI6Ii8zNjcyOTI5Ni8zMTAzNDE1MjAtYjVhYmEzMDEtMmQ5NC00YjI0LWFkMzgtN2Y4YzFhNmM0Y2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Mjg3NWE1Y2VjMjZkNjIxOWMxOWU2M2YzNDQ4NjA5MWMwYzFlMWM3NzhlNDhiYTkxNDY0MjcyNGY0OWMyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ali69oGphWhEvzfPvkSbnuy36QJpSgcicQfm6gjSXo)
> > > 
> > > 
> > > 有没有可能这是在刷屏呢
> > 
> > 
> > 对比了一下，app上面也没有多条重复的，还是说app做了限制重复刷屏的显示
> 
> 前端可以控制如何展示数据，虎牙APP和网页都有屏蔽重复弹幕的开关 <img alt="image" width="311" src="https://private-user-images.githubusercontent.com/43869694/310395701-9829047f-742b-414d-b44a-02f5c9ed4f22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTE2NDgsIm5iZiI6MTcwOTcxMTM0OCwicGF0aCI6Ii80Mzg2OTY5NC8zMTAzOTU3MDEtOTgyOTA0N2YtNzQyYi00MTRkLWI0NGEtMDJmNWM5ZWQ0ZjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA3NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YmViMDcwM2JmMjUyMWRiYjJhY2UwYjFjYTdhOWJhN2U3ZTgwNzkxZjBkNzU2MTRiZjRhZjU2NDJlY2M3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DSj_YZAMrCkdU4_L3BjZsch1rtLVQZQ-jJBwHo_8tvc">

原来如此，谢谢解答！
