### ISSUE TITLE
🙋 问题交流。。。 | [Question] 部分抖音直播间，连接socket状态码错误

### ISSUE THREAD

**Issue by skipper-sj** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#98]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
最新版本

### 预期行为 | Expected behavior
成功连接socket
### 实际行为 | Actual behavior
连接抖音直播间，提示，如房间id：193059181093
ERROR tech.ordinaryroad.live.chat.client.servers.netty.handler.base.BaseConnectionHandler -- 握手失败！status:200 OK

**Comment by 1962247851** [comment]
老哥用的版本号具体是多少？

**Comment by 1962247851** [comment]
0.3.0起用的内置的WebSocket协议处理器，不会打印`握手失败！status:xxx`

**Comment by 1962247851** [comment]
请更新到最新版本:)
